/**
 * Error Codes - Backend
 * Centralized error code definitions
 */

const ErrorCodes = {
    // Authentication Errors (1000-1099)
    AUTH_INVALID_CREDENTIALS: 'AUTH_1001',
    AUTH_EMAIL_NOT_FOUND: 'AUTH_1002',
    AUTH_ACCOUNT_DISABLED: 'AUTH_1003',
    AUTH_ACCOUNT_NOT_VERIFIED: 'AUTH_1004',
    AUTH_INVALID_TOKEN: 'AUTH_1005',
    AUTH_TOKEN_EXPIRED: 'AUTH_1006',
    AUTH_REFRESH_TOKEN_INVALID: 'AUTH_1007',
    AUTH_REFRESH_TOKEN_EXPIRED: 'AUTH_1008',
    AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_1009',
    AUTH_WEAK_PASSWORD: 'AUTH_1010',
    AUTH_PASSWORD_MISMATCH: 'AUTH_1011',
    AUTH_OTP_INVALID: 'AUTH_1012',
    AUTH_OTP_EXPIRED: 'AUTH_1013',
    AUTH_OTP_ALREADY_USED: 'AUTH_1014',
    AUTH_TOO_MANY_ATTEMPTS: 'AUTH_1015',
    AUTH_SESSION_EXPIRED: 'AUTH_1016',
    AUTH_UNAUTHORIZED: 'AUTH_1017',
    AUTH_OLD_PASSWORD_INCORRECT: 'AUTH_1018',
    AUTH_OTP_RESEND_TOO_SOON: 'AUTH_1019',
    AUTH_OTP_MAX_ATTEMPTS: 'AUTH_1020',

    // User Errors (1100-1199)
    USER_NOT_FOUND: 'USER_1101',
    USER_PROFILE_INCOMPLETE: 'USER_1102',
    USER_ALREADY_FOLLOWING: 'USER_1103',
    USER_NOT_FOLLOWING: 'USER_1104',
    USER_CANNOT_FOLLOW_SELF: 'USER_1105',
    USER_ALLERGY_INVALID: 'USER_1106',

    // Post Errors (1200-1299)
    POST_NOT_FOUND: 'POST_1201',
    POST_UNAUTHORIZED: 'POST_1202',
    POST_ALREADY_RATED: 'POST_1203',
    POST_RATING_INVALID: 'POST_1204',
    POST_TITLE_REQUIRED: 'POST_1205',
    POST_DESCRIPTION_REQUIRED: 'POST_1206',
    POST_TAGS_REQUIRED: 'POST_1207',
    POST_IMAGE_REQUIRED: 'POST_1208',
    POST_ALREADY_SAVED: 'POST_1209',
    POST_NOT_SAVED: 'POST_1210',
    POST_CANNOT_REPOST_OWN: 'POST_1211',
    POST_ALREADY_REPOSTED: 'POST_1212',

    // Comment Errors (1300-1399)
    COMMENT_NOT_FOUND: 'COMMENT_1301',
    COMMENT_UNAUTHORIZED: 'COMMENT_1302',
    COMMENT_CONTENT_REQUIRED: 'COMMENT_1303',
    COMMENT_TOO_LONG: 'COMMENT_1304',

    // Recipe Errors (1400-1499)
    RECIPE_NOT_FOUND: 'RECIPE_1401',
    RECIPE_INGREDIENTS_REQUIRED: 'RECIPE_1402',
    RECIPE_STEPS_REQUIRED: 'RECIPE_1403',
    RECIPE_COOKING_TIME_INVALID: 'RECIPE_1404',
    RECIPE_SERVINGS_INVALID: 'RECIPE_1405',
    RECIPE_DIFFICULTY_INVALID: 'RECIPE_1406',

    // Meal Plan Errors (1500-1599)
    MEAL_PLAN_NOT_FOUND: 'MEAL_PLAN_1501',
    MEAL_PLAN_UNAUTHORIZED: 'MEAL_PLAN_1502',
    MEAL_PLAN_DATE_INVALID: 'MEAL_PLAN_1503',
    MEAL_PLAN_ALREADY_EXISTS: 'MEAL_PLAN_1504',

    // File/Upload Errors (1600-1699)
    FILE_NOT_FOUND: 'FILE_1601',
    FILE_TOO_LARGE: 'FILE_1602',
    FILE_TYPE_INVALID: 'FILE_1603',
    FILE_UPLOAD_FAILED: 'FILE_1604',
    IMAGE_INVALID_FORMAT: 'FILE_1605',
    IMAGE_TOO_LARGE: 'FILE_1606',

    // Search Errors (1700-1799)
    SEARCH_QUERY_REQUIRED: 'SEARCH_1701',
    SEARCH_QUERY_TOO_SHORT: 'SEARCH_1702',
    SEARCH_NO_RESULTS: 'SEARCH_1703',

    // AI Errors (1800-1899)
    AI_SERVICE_UNAVAILABLE: 'AI_1801',
    AI_INVALID_REQUEST: 'AI_1802',
    AI_QUOTA_EXCEEDED: 'AI_1803',
    AI_IMAGE_RECOGNITION_FAILED: 'AI_1804',
    AI_MENU_GENERATION_FAILED: 'AI_1805',
    AI_NUTRITION_ANALYSIS_FAILED: 'AI_1806',

    // Notification Errors (1900-1999)
    NOTIFICATION_NOT_FOUND: 'NOTIFICATION_1901',
    NOTIFICATION_ALREADY_READ: 'NOTIFICATION_1902',

    // Validation Errors (2000-2099)
    VALIDATION_FAILED: 'VALIDATION_2001',
    VALIDATION_EMAIL_INVALID: 'VALIDATION_2002',
    VALIDATION_REQUIRED_FIELD: 'VALIDATION_2003',
    VALIDATION_FIELD_TOO_LONG: 'VALIDATION_2004',
    VALIDATION_FIELD_TOO_SHORT: 'VALIDATION_2005',
    VALIDATION_INVALID_FORMAT: 'VALIDATION_2006',
    VALIDATION_INVALID_VALUE: 'VALIDATION_2007',
    VALIDATION_ERROR: 'VALIDATION_2008',

    // Server Errors (5000-5099)
    SERVER_ERROR: 'SERVER_5001',
    DATABASE_ERROR: 'SERVER_5002',
    EXTERNAL_SERVICE_ERROR: 'SERVER_5003',
    TIMEOUT_ERROR: 'SERVER_5004',

    // Rate Limiting (4000-4099)
    RATE_LIMIT_EXCEEDED: 'RATE_4001',
    TOO_MANY_REQUESTS: 'RATE_4002',
};

// HTTP Status Code mapping
const ErrorStatusCodes = {
    // 400 Bad Request
    [ErrorCodes.VALIDATION_FAILED]: 400,
    [ErrorCodes.VALIDATION_EMAIL_INVALID]: 400,
    [ErrorCodes.VALIDATION_REQUIRED_FIELD]: 400,
    [ErrorCodes.VALIDATION_FIELD_TOO_LONG]: 400,
    [ErrorCodes.VALIDATION_FIELD_TOO_SHORT]: 400,
    [ErrorCodes.VALIDATION_INVALID_FORMAT]: 400,
    [ErrorCodes.VALIDATION_INVALID_VALUE]: 400,
    [ErrorCodes.POST_TITLE_REQUIRED]: 400,
    [ErrorCodes.POST_DESCRIPTION_REQUIRED]: 400,
    [ErrorCodes.POST_TAGS_REQUIRED]: 400,
    [ErrorCodes.RECIPE_INGREDIENTS_REQUIRED]: 400,
    [ErrorCodes.RECIPE_STEPS_REQUIRED]: 400,
    [ErrorCodes.SEARCH_QUERY_REQUIRED]: 400,
    [ErrorCodes.SEARCH_QUERY_TOO_SHORT]: 400,
    [ErrorCodes.COMMENT_CONTENT_REQUIRED]: 400,

    // 401 Unauthorized
    [ErrorCodes.AUTH_INVALID_CREDENTIALS]: 401,
    [ErrorCodes.AUTH_INVALID_TOKEN]: 401,
    [ErrorCodes.AUTH_TOKEN_EXPIRED]: 401,
    [ErrorCodes.AUTH_UNAUTHORIZED]: 401,
    [ErrorCodes.AUTH_SESSION_EXPIRED]: 401,
    [ErrorCodes.AUTH_REFRESH_TOKEN_INVALID]: 401,
    [ErrorCodes.AUTH_REFRESH_TOKEN_EXPIRED]: 401,

    // 403 Forbidden
    [ErrorCodes.AUTH_ACCOUNT_DISABLED]: 403,
    [ErrorCodes.POST_UNAUTHORIZED]: 403,
    [ErrorCodes.COMMENT_UNAUTHORIZED]: 403,
    [ErrorCodes.MEAL_PLAN_UNAUTHORIZED]: 403,

    // 404 Not Found
    [ErrorCodes.USER_NOT_FOUND]: 404,
    [ErrorCodes.POST_NOT_FOUND]: 404,
    [ErrorCodes.COMMENT_NOT_FOUND]: 404,
    [ErrorCodes.RECIPE_NOT_FOUND]: 404,
    [ErrorCodes.FILE_NOT_FOUND]: 404,
    [ErrorCodes.NOTIFICATION_NOT_FOUND]: 404,
    [ErrorCodes.MEAL_PLAN_NOT_FOUND]: 404,
    [ErrorCodes.AUTH_EMAIL_NOT_FOUND]: 404,
    [ErrorCodes.SEARCH_NO_RESULTS]: 404,

    // 409 Conflict
    [ErrorCodes.AUTH_EMAIL_ALREADY_EXISTS]: 409,
    [ErrorCodes.POST_ALREADY_SAVED]: 409,
    [ErrorCodes.POST_ALREADY_REPOSTED]: 409,
    [ErrorCodes.POST_ALREADY_RATED]: 409,
    [ErrorCodes.USER_ALREADY_FOLLOWING]: 409,
    [ErrorCodes.MEAL_PLAN_ALREADY_EXISTS]: 409,
    [ErrorCodes.NOTIFICATION_ALREADY_READ]: 409,

    // 413 Payload Too Large
    [ErrorCodes.FILE_TOO_LARGE]: 413,
    [ErrorCodes.IMAGE_TOO_LARGE]: 413,

    // 422 Unprocessable Entity
    [ErrorCodes.AUTH_WEAK_PASSWORD]: 422,
    [ErrorCodes.AUTH_PASSWORD_MISMATCH]: 422,
    [ErrorCodes.AUTH_OTP_INVALID]: 422,
    [ErrorCodes.AUTH_OTP_EXPIRED]: 422,
    [ErrorCodes.AUTH_OTP_ALREADY_USED]: 422,
    [ErrorCodes.AUTH_OTP_RESEND_TOO_SOON]: 422,
    [ErrorCodes.AUTH_OLD_PASSWORD_INCORRECT]: 422,
    [ErrorCodes.AUTH_ACCOUNT_NOT_VERIFIED]: 422,
    [ErrorCodes.FILE_TYPE_INVALID]: 422,
    [ErrorCodes.IMAGE_INVALID_FORMAT]: 422,
    [ErrorCodes.POST_RATING_INVALID]: 422,
    [ErrorCodes.POST_CANNOT_REPOST_OWN]: 422,
    [ErrorCodes.USER_CANNOT_FOLLOW_SELF]: 422,
    [ErrorCodes.USER_NOT_FOLLOWING]: 422,
    [ErrorCodes.USER_ALLERGY_INVALID]: 422,
    [ErrorCodes.RECIPE_COOKING_TIME_INVALID]: 422,
    [ErrorCodes.RECIPE_SERVINGS_INVALID]: 422,
    [ErrorCodes.RECIPE_DIFFICULTY_INVALID]: 422,
    [ErrorCodes.MEAL_PLAN_DATE_INVALID]: 422,
    [ErrorCodes.COMMENT_TOO_LONG]: 422,

    // 429 Too Many Requests
    [ErrorCodes.RATE_LIMIT_EXCEEDED]: 429,
    [ErrorCodes.TOO_MANY_REQUESTS]: 429,
    [ErrorCodes.AUTH_TOO_MANY_ATTEMPTS]: 429,
    [ErrorCodes.AUTH_OTP_MAX_ATTEMPTS]: 429,

    // 500 Internal Server Error
    [ErrorCodes.SERVER_ERROR]: 500,
    [ErrorCodes.DATABASE_ERROR]: 500,
    [ErrorCodes.FILE_UPLOAD_FAILED]: 500,

    // 503 Service Unavailable
    [ErrorCodes.AI_SERVICE_UNAVAILABLE]: 503,
    [ErrorCodes.EXTERNAL_SERVICE_ERROR]: 503,
    [ErrorCodes.AI_QUOTA_EXCEEDED]: 503,
    [ErrorCodes.AI_INVALID_REQUEST]: 503,
    [ErrorCodes.AI_IMAGE_RECOGNITION_FAILED]: 503,
    [ErrorCodes.AI_MENU_GENERATION_FAILED]: 503,
    [ErrorCodes.AI_NUTRITION_ANALYSIS_FAILED]: 503,

    // 504 Gateway Timeout
    [ErrorCodes.TIMEOUT_ERROR]: 504,
};

module.exports = {
    ErrorCodes,
    ErrorStatusCodes,
};
